name: Release keycloak-subgroup-claim-mapper

on:
  push:
    tags:
      - '*.*.*'

env:
  CURRENT_REF: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: inventage-ephemeral-linux-amd64

    steps:
      - name: Fetching the source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install needed binaries
        run: |
          sudo apt-get update

          echo "💾 Installing 'mvn'"
          sudo apt-get install maven  --yes

          sudo apt-get clean

      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion="${CURRENT_REF}"

      - name: Build with Maven
        run: mvn clean package

      - name: Get JAR file name
        id: get-jar
        run: echo "JAR_FILE=$(ls target/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            - Feature a
            - Feature b
            - ...

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_FILE }}
          asset_name: keycloak-subgroup-claim-mapper-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
